In [1]:
bool()

False

In [1]:
type(True)

bool

In [2]:
# shift + tab on function to get more info 
my_str = 'hello'
my_str.isdigit() # many more functions like this exists

False

### LISTS

In [3]:
type([])

list

In [4]:
lst = []

In [7]:
lst = ['hello', '13abc', 900]

In [8]:
lst

['hello', '13abc', 900]

In [9]:
lst.append('this was added') # there is also extend function 

In [10]:
lst

['hello', '13abc', 900, 'this was added']

In [11]:
len(lst)

4

In [13]:
# selecting a part of the list 
lst[1:]

['13abc', 900, 'this was added']

In [39]:
# can perform operations on the list 
lst_num = [1,2,3,4,5,1,1]
sum(lst_num)

17

In [40]:
lst_num.pop()

1

In [42]:
max(lst_num)

5

In [43]:
lst_small = [1,2,3]

In [45]:
# this duplicates the list 
lst_small*2

[1, 2, 3, 1, 2, 3]

In [46]:
# multiply content in list, there are lots of ways 
list(map(lambda x: x*2, lst_small))


[2, 4, 6]

## SETS
unordered, iterable, no duplicated elements. 

In [48]:
set_my = {'bob', 'adam', 23, 111}
print(set_my)

{'adam', 23, 111, 'bob'}


In [49]:
# adding to a set, using inbuilt function
set_my.add("dad")
print(set_my)
# functions like Union... that can be performed on two sets exists. And many more 

{111, 'bob', 23, 'adam', 'dad'}


## DICTIONARY
* unsorted collection
* can index 
* key value pairs 

In [50]:
dicnry = {'car1': 'bmw', 'car2': 'volvo', 'car3': 'honda'}

In [51]:
dicnry

{'car1': 'bmw', 'car2': 'volvo', 'car3': 'honda'}

In [52]:
dicnry['car1']

'bmw'

In [53]:
#looping thru 
for x in dicnry:
    print(x)

car1
car2
car3


In [54]:
#loop values
for x in dicnry.values():
    print(x)

bmw
volvo
honda


In [55]:
# loop key and values
for x in dicnry.items():
    print(x)

('car1', 'bmw')
('car2', 'volvo')
('car3', 'honda')


In [56]:
# adding new items 
dicnry['car4'] = 'truck'

In [57]:
dicnry

{'car1': 'bmw', 'car2': 'volvo', 'car3': 'honda', 'car4': 'truck'}

In [58]:
# edit existing key's values
dicnry['car1'] = 'police car'

In [59]:
dicnry

{'car1': 'police car', 'car2': 'volvo', 'car3': 'honda', 'car4': 'truck'}

### Nested dict

In [60]:
fruit1_num = {'apple':3}
fruit2_num = {'banana': 1}
fruit3_num = {'lemon': 5}

fruit_type = {'fruit1': fruit1_num, 'fruit2': fruit2_num, 'fruit3': fruit3_num}

In [61]:
print(fruit_type)

{'fruit1': {'apple': 3}, 'fruit2': {'banana': 1}, 'fruit3': {'lemon': 5}}


In [62]:
print(fruit_type['fruit1'])

{'apple': 3}


In [63]:
print(fruit_type['fruit1']['apple'])

3


### Tuple
CANT change the elements afterwards

In [64]:
my_tuple = ('josh', 'eva', 'jon')

In [65]:
my_tuple[1]

'eva'

# NUMPY

In [1]:
import numpy as np

In [3]:
my_lst = [1,2,3,4,5]
arr = np.array(my_lst)

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr

array([1, 2, 3, 4, 5])

In [6]:
# multinested array 
a = [1,2,3]
b = [4,5,6]
c = [7,8,9]
arr = np.array([a, b, c])

In [7]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arr.shape

(3, 3)

In [11]:
#copy
arr = [range(10)]

In [29]:
arr = []
arr.extend(range(1, 11))
arr = np.array(arr)

In [30]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
arr[3:] = 100

In [33]:
arr

array([  1,   2,   3, 100, 100, 100, 100, 100, 100, 100])

In [35]:
# conditon
arr<50

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [36]:
arr[arr<50]

array([1, 2, 3])

In [38]:
# randomize some ints 
np.random.randint(0,100,3)

array([ 2, 71, 25])

## PANDAS 

In [3]:
import pandas as pd 
import numpy as np

In [4]:
df = pd.DataFrame(np.arange(0,20).reshape(5,4),index=['Row1', 'Row2', 'Row3', 'Row4', 'Row5'],columns=['Column1','Column2','Column3','Column4'])

In [5]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19